<?php
/**
 * @var $block Veni\RegisteredCustomersReport\Block\Adminhtml\EmailContentRender
 */
?>

<?php
$data = $block->getCustomersData();
?>

<?php
if(!empty($data['customers'])): ?>
    <table border="1" cellpadding="5">
        <thead>
            <tr align="center">
                <?php
                foreach ($data['labels'] as $label): ?>
                    <th><?= $label ?></th>
                <?php
                endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($data['customers'] as $customer): ?>
                <tr>
                    <?php
                    foreach ($customer->getData() as $key => $value): ?>
                        <td><?= $value; ?></td>
                    <?php
                    endforeach; ?>
                </tr>
            <?php
            endforeach; ?>
        </tbody>
    </table>
<?php
else:
   echo  __('No customers have registered within the last  hours.');
endif; ?>