<?php
/**
 * @var $block Veni\RegisteredCustomersReport\Block\Adminhtml\EmailContentRender
 */
?>

<?php
$data = $block->getCustomersData();
//$dbCustomer = $this->helper('\Veni\RegisteredCustomersReport\Helper\DatabaseCustomerManager');
?>

<?php
if(!empty($data['customers'])): ?>
    <table border="1" cellpadding="5">
        <thead>
            <tr align="center">
                <?php
                foreach ($data['labels'] as $label): ?>
                    <th><?= $label ?></th>
                <?php
                endforeach; ?>
            </tr>
        </thead>
    <?php
    foreach ($data['customers'] as $value): ?>
        <tbody>
            <tr>
                <td><?= $value ?></td>
            </tr>
        </tbody>
    <?php
    endforeach; ?>
    </table>
<?php
else:
   echo  __('No customers have registered within the last  hours.');
endif; ?>